{pkgs}: {
  deps = [
    pkgs.chromium
    pkgs.alsa-lib
    pkgs.cairo
    pkgs.pango
    pkgs.mesa
    pkgs.xorg.libXrandr
    pkgs.xorg.libXfixes
    pkgs.xorg.libXext
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.xorg.libX11
    pkgs.xorg.libxcb
    pkgs.libdrm
    pkgs.expat
    pkgs.dbus
    pkgs.cups
    pkgs.at-spi2-core
    pkgs.nspr
    pkgs.nss
    pkgs.glib
    pkgs.rsync
    pkgs.sshpass
    pkgs.openssh
    pkgs.unzip
    pkgs.flutter
    pkgs.psmisc
    pkgs.jq
    pkgs.postgresql
  ];
}
