/**
 * @package @molochain/shared-permissions
 * RBAC Permission System
 * Centralized permission matrix for admin panel access control
 */

export {
  PERMISSION_DOMAINS,
  PERMISSIONS,
  ADMIN_ROLES,
  type Permission,
  type AdminRole,
  type RolePermissionMap,
  type PermissionDomain,
} from './types';

import {
  PERMISSIONS,
  ADMIN_ROLES,
  type Permission,
  type AdminRole,
  type RolePermissionMap,
} from './types';

export const ROLE_PERMISSIONS: RolePermissionMap = {
  [ADMIN_ROLES.SUPER_ADMIN]: [
    PERMISSIONS.SYSTEM_SUPER_ADMIN,
    PERMISSIONS.SYSTEM_ADMIN,
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_EDIT,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.SECURITY_EDIT,
    PERMISSIONS.SECURITY_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_EDIT,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_EDIT,
    PERMISSIONS.CONTENT_DELETE,
    PERMISSIONS.CONTENT_PUBLISH,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.OPERATIONS_EDIT,
    PERMISSIONS.OPERATIONS_MANAGE,
    PERMISSIONS.INTELLIGENCE_VIEW,
    PERMISSIONS.INTELLIGENCE_EDIT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EDIT,
    PERMISSIONS.INTEGRATIONS_VIEW,
    PERMISSIONS.INTEGRATIONS_EDIT,
    PERMISSIONS.INTEGRATIONS_MANAGE,
    PERMISSIONS.INFRASTRUCTURE_VIEW,
    PERMISSIONS.INFRASTRUCTURE_EDIT,
    PERMISSIONS.INFRASTRUCTURE_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_MANAGE,
  ],
  [ADMIN_ROLES.ADMIN]: [
    PERMISSIONS.SYSTEM_ADMIN,
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_EDIT,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.SECURITY_EDIT,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_EDIT,
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_EDIT,
    PERMISSIONS.CONTENT_PUBLISH,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.OPERATIONS_EDIT,
    PERMISSIONS.INTELLIGENCE_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.INTEGRATIONS_VIEW,
    PERMISSIONS.INTEGRATIONS_EDIT,
    PERMISSIONS.INFRASTRUCTURE_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  [ADMIN_ROLES.MANAGER]: [
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.CONTENT_EDIT,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.OPERATIONS_EDIT,
    PERMISSIONS.OPERATIONS_MANAGE,
    PERMISSIONS.INTELLIGENCE_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.INTEGRATIONS_VIEW,
    PERMISSIONS.INFRASTRUCTURE_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  [ADMIN_ROLES.ANALYST]: [
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.INTELLIGENCE_VIEW,
    PERMISSIONS.INTELLIGENCE_EDIT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EDIT,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  [ADMIN_ROLES.DEVELOPER]: [
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.INTEGRATIONS_VIEW,
    PERMISSIONS.INTEGRATIONS_EDIT,
    PERMISSIONS.INTEGRATIONS_MANAGE,
    PERMISSIONS.INFRASTRUCTURE_VIEW,
    PERMISSIONS.INFRASTRUCTURE_EDIT,
    PERMISSIONS.INFRASTRUCTURE_MANAGE,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  [ADMIN_ROLES.MODERATOR]: [
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_EDIT,
    PERMISSIONS.CONTENT_DELETE,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  [ADMIN_ROLES.EXECUTIVE]: [
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.INTELLIGENCE_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
};

export function hasPermission(userRole: AdminRole | string, permission: Permission): boolean {
  const role = userRole as AdminRole;
  const rolePermissions = ROLE_PERMISSIONS[role];
  
  if (!rolePermissions) {
    return false;
  }
  
  if (rolePermissions.includes(PERMISSIONS.SYSTEM_SUPER_ADMIN)) {
    return true;
  }
  
  return rolePermissions.includes(permission);
}

export function hasAnyPermission(userRole: AdminRole | string, permissions: Permission[]): boolean {
  return permissions.some(permission => hasPermission(userRole, permission));
}

export function hasAllPermissions(userRole: AdminRole | string, permissions: Permission[]): boolean {
  return permissions.every(permission => hasPermission(userRole, permission));
}

export function getRolePermissions(role: AdminRole | string): Permission[] {
  return ROLE_PERMISSIONS[role as AdminRole] || [];
}

export function isValidAdminRole(role: string): role is AdminRole {
  return Object.values(ADMIN_ROLES).includes(role as AdminRole);
}

export function getAllAdminRoles(): AdminRole[] {
  return Object.values(ADMIN_ROLES);
}

export function getAllPermissions(): Permission[] {
  return Object.values(PERMISSIONS);
}
