/**
 * RBAC Permission System
 * Centralized permission matrix for admin panel access control
 * 
 * NOTE: This file re-exports from @molochain/shared-permissions for backward compatibility.
 * For new code, consider importing directly from 'packages/shared-permissions'.
 */

export {
  PERMISSION_DOMAINS,
  PERMISSIONS,
  ADMIN_ROLES,
  ROLE_PERMISSIONS,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
  getRolePermissions,
  isValidAdminRole,
  getAllAdminRoles,
  getAllPermissions,
  type Permission,
  type AdminRole,
  type RolePermissionMap,
  type PermissionDomain,
} from '../packages/shared-permissions';

import { PERMISSION_DOMAINS, PERMISSIONS, type Permission } from '../packages/shared-permissions';

export const PERMISSIONS_BY_DOMAIN: Record<string, Permission[]> = {
  [PERMISSION_DOMAINS.DASHBOARD]: [
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_EDIT,
  ],
  [PERMISSION_DOMAINS.USERS]: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_MANAGE,
  ],
  [PERMISSION_DOMAINS.SECURITY]: [
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.SECURITY_EDIT,
    PERMISSIONS.SECURITY_MANAGE,
  ],
  [PERMISSION_DOMAINS.SETTINGS]: [
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_EDIT,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  [PERMISSION_DOMAINS.CONTENT]: [
    PERMISSIONS.CONTENT_VIEW,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_EDIT,
    PERMISSIONS.CONTENT_DELETE,
    PERMISSIONS.CONTENT_PUBLISH,
  ],
  [PERMISSION_DOMAINS.OPERATIONS]: [
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.OPERATIONS_EDIT,
    PERMISSIONS.OPERATIONS_MANAGE,
  ],
  [PERMISSION_DOMAINS.INTELLIGENCE]: [
    PERMISSIONS.INTELLIGENCE_VIEW,
    PERMISSIONS.INTELLIGENCE_EDIT,
  ],
  [PERMISSION_DOMAINS.ANALYTICS]: [
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EDIT,
  ],
  [PERMISSION_DOMAINS.INTEGRATIONS]: [
    PERMISSIONS.INTEGRATIONS_VIEW,
    PERMISSIONS.INTEGRATIONS_EDIT,
    PERMISSIONS.INTEGRATIONS_MANAGE,
  ],
  [PERMISSION_DOMAINS.INFRASTRUCTURE]: [
    PERMISSIONS.INFRASTRUCTURE_VIEW,
    PERMISSIONS.INFRASTRUCTURE_EDIT,
    PERMISSIONS.INFRASTRUCTURE_MANAGE,
  ],
  [PERMISSION_DOMAINS.AUDIT]: [
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_MANAGE,
  ],
};
