import { pgTable, serial, text, timestamp, json, integer, boolean, decimal, varchar } from 'drizzle-orm/pg-core';
import { createInsertSchema } from 'drizzle-zod';
import { z } from 'zod';

/**
 * Rayanava AI Content Generation Table
 * Stores all content generated by Rayanava for marketing and sales
 */
export const aiGeneratedContent = pgTable('ai_generated_content', {
  id: serial('id').primaryKey(),
  type: text('type').notNull(), // blog, social, email, landing, success_story
  topic: text('topic'),
  keywords: json('keywords').$type<string[]>(),
  tone: text('tone'), // professional, casual, technical, inspiring
  length: text('length'), // short, medium, long
  content: json('content').notNull(),
  metadata: json('metadata'),
  generatedBy: text('generated_by').default('rayanava'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow()
});

/**
 * Rayanava Sales Leads Table
 * Stores leads and their qualification data
 */
export const aiSalesLeads = pgTable('ai_sales_leads', {
  id: serial('id').primaryKey(),
  leadId: text('lead_id').unique().notNull(),
  company: text('company'),
  companySize: integer('company_size'),
  industry: text('industry'),
  contactName: text('contact_name'),
  email: text('email'),
  phone: text('phone'),
  source: text('source'),
  score: integer('score').default(0),
  qualification: text('qualification'), // SQL, MQL, Lead
  priority: text('priority'), // high, medium, low
  segment: text('segment'), // Enterprise, Mid-Market, SMB, Startup
  estimatedValue: decimal('estimated_value', { precision: 10, scale: 2 }),
  conversionProbability: integer('conversion_probability'),
  assignedTo: text('assigned_to'),
  engagement: json('engagement').$type<{
    website_visits?: number;
    content_downloads?: number;
    demo_requested?: boolean;
    webinar_attended?: boolean;
  }>(),
  budget: text('budget'),
  timeline: text('timeline'),
  painPoints: json('pain_points').$type<string[]>(),
  notes: text('notes'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow()
});

/**
 * Rayanava Sales Opportunities Table
 * Tracks sales opportunities and pipeline
 */
export const aiSalesOpportunities = pgTable('ai_sales_opportunities', {
  id: serial('id').primaryKey(),
  opportunityId: text('opportunity_id').unique().notNull(),
  leadId: text('lead_id').references(() => aiSalesLeads.leadId),
  company: text('company'),
  value: decimal('value', { precision: 10, scale: 2 }),
  stage: text('stage'), // Qualification, Discovery, Demo, Proposal, Negotiation, Closed Won/Lost
  closeDate: timestamp('close_date'),
  probability: integer('probability'),
  healthScore: integer('health_score'),
  competitors: json('competitors').$type<string[]>(),
  decisionMakers: json('decision_makers').$type<any[]>(),
  risks: json('risks').$type<string[]>(),
  accelerators: json('accelerators').$type<string[]>(),
  notes: text('notes'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow()
});

/**
 * Rayanava Follow-up Activities Table
 * Stores follow-up activities and communications
 */
export const aiFollowUpActivities = pgTable('ai_follow_up_activities', {
  id: serial('id').primaryKey(),
  leadId: text('lead_id').references(() => aiSalesLeads.leadId),
  opportunityId: text('opportunity_id').references(() => aiSalesOpportunities.opportunityId),
  type: text('type').notNull(), // email, call, meeting, linkedin, nurture
  subject: text('subject'),
  message: text('message'),
  scheduledFor: timestamp('scheduled_for'),
  completedAt: timestamp('completed_at'),
  status: text('status').default('pending'), // pending, sent, completed, cancelled
  response: text('response'),
  nextAction: text('next_action'),
  createdAt: timestamp('created_at').defaultNow()
});

/**
 * Rayanava Chat History Table
 * Stores all chat interactions with Rayanava
 */
export const aiChatHistory = pgTable('ai_chat_history', {
  id: serial('id').primaryKey(),
  sessionId: text('session_id').notNull(),
  userId: integer('user_id'),
  message: text('message').notNull(),
  response: text('response').notNull(),
  context: json('context'),
  metadata: json('metadata'),
  createdAt: timestamp('created_at').defaultNow()
});

/**
 * Rayanava Workflows Table
 * Stores executed workflows and their results
 */
export const aiWorkflows = pgTable('ai_workflows', {
  id: serial('id').primaryKey(),
  workflowId: text('workflow_id').notNull(),
  name: text('name'),
  type: text('type'),
  inputData: json('input_data'),
  outputData: json('output_data'),
  status: text('status').default('pending'), // pending, running, completed, failed
  error: text('error'),
  executionTime: integer('execution_time'), // in milliseconds
  createdAt: timestamp('created_at').defaultNow(),
  completedAt: timestamp('completed_at')
});

/**
 * Rayanava Analytics Table
 * Stores AI performance metrics and analytics
 */
export const aiAnalytics = pgTable('ai_analytics', {
  id: serial('id').primaryKey(),
  metric: text('metric').notNull(),
  value: decimal('value', { precision: 10, scale: 2 }),
  category: text('category'), // content, sales, operations, performance
  period: text('period'), // daily, weekly, monthly
  metadata: json('metadata'),
  createdAt: timestamp('created_at').defaultNow()
});

// Insert schemas
export const insertAiGeneratedContentSchema = createInsertSchema(aiGeneratedContent).omit({ id: true, createdAt: true, updatedAt: true });
export const insertAiSalesLeadSchema = createInsertSchema(aiSalesLeads).omit({ id: true, createdAt: true, updatedAt: true });
export const insertAiSalesOpportunitySchema = createInsertSchema(aiSalesOpportunities).omit({ id: true, createdAt: true, updatedAt: true });
export const insertAiFollowUpActivitySchema = createInsertSchema(aiFollowUpActivities).omit({ id: true, createdAt: true });
export const insertAiChatHistorySchema = createInsertSchema(aiChatHistory).omit({ id: true, createdAt: true });
export const insertAiWorkflowSchema = createInsertSchema(aiWorkflows).omit({ id: true, createdAt: true });
export const insertAiAnalyticsSchema = createInsertSchema(aiAnalytics).omit({ id: true, createdAt: true });

// Types
export type InsertAiGeneratedContent = z.infer<typeof insertAiGeneratedContentSchema>;
export type InsertAiSalesLead = z.infer<typeof insertAiSalesLeadSchema>;
export type InsertAiSalesOpportunity = z.infer<typeof insertAiSalesOpportunitySchema>;
export type InsertAiFollowUpActivity = z.infer<typeof insertAiFollowUpActivitySchema>;
export type InsertAiChatHistory = z.infer<typeof insertAiChatHistorySchema>;
export type InsertAiWorkflow = z.infer<typeof insertAiWorkflowSchema>;
export type InsertAiAnalytics = z.infer<typeof insertAiAnalyticsSchema>;

export type AiGeneratedContent = typeof aiGeneratedContent.$inferSelect;
export type AiSalesLead = typeof aiSalesLeads.$inferSelect;
export type AiSalesOpportunity = typeof aiSalesOpportunities.$inferSelect;
export type AiFollowUpActivity = typeof aiFollowUpActivities.$inferSelect;
export type AiChatHistory = typeof aiChatHistory.$inferSelect;
export type AiWorkflow = typeof aiWorkflows.$inferSelect;
export type AiAnalytics = typeof aiAnalytics.$inferSelect;