import crypto from 'crypto';
import { db } from '../db';
import { 
  ecosystemServices, 
  ecosystemWebhooks, 
  ecosystemApiDocs,
  externalApiKeys 
} from '@shared/schema';
import { eq } from 'drizzle-orm';

const API_KEY_PREFIX = 'mk_eco_';
const API_SECRET_PREFIX = 'msk_eco_';

function generateApiKey(): string {
  const randomBytes = crypto.randomBytes(24).toString('hex');
  return `${API_KEY_PREFIX}${randomBytes}`;
}

function generateApiSecret(): string {
  const randomBytes = crypto.randomBytes(32).toString('hex');
  return `${API_SECRET_PREFIX}${randomBytes}`;
}

function generateWebhookSecret(): string {
  return crypto.randomBytes(32).toString('hex');
}

function hashKey(key: string): string {
  return crypto.createHash('sha256').update(key).digest('hex');
}

async function seedRayanavaIntegration() {
  console.log('🚀 Starting RAYANAVA integration seeding...\n');

  try {
    const existingService = await db.select().from(ecosystemServices)
      .where(eq(ecosystemServices.slug, 'rayanava'))
      .limit(1);

    if (existingService.length > 0) {
      console.log('⚠️  RAYANAVA service already exists. Skipping creation.');
      console.log('   Service ID:', existingService[0].id);
      return existingService[0];
    }

    console.log('📝 Creating RAYANAVA service registration...');

    const webhookSecret = generateWebhookSecret();
    const baseUrl = process.env.RAYANAVA_BASE_URL || 'http://localhost:5000/api/rayanava';

    const [rayanavaService] = await db.insert(ecosystemServices).values({
      name: 'RAYANAVA AI Gateway',
      slug: 'rayanava',
      description: 'Molochain AI Assistant powered by advanced language models. Provides intelligent automation, natural language processing, and cognitive assistance for the ecosystem.',
      baseUrl,
      healthEndpoint: '/health',
      webhookSecret,
      status: 'active',
      healthCheckInterval: 60,
      metadata: {
        version: '1.0.0',
        maintainer: 'Molochain AI Team',
        environment: (process.env.NODE_ENV as 'development' | 'staging' | 'production') || 'development',
        tags: ['ai', 'nlp', 'automation', 'assistant'],
        capabilities: [
          'natural-language-understanding',
          'content-generation',
          'code-assistance',
          'data-analysis',
          'workflow-automation'
        ],
      },
    }).returning();

    console.log('✅ RAYANAVA service created');
    console.log('   Service ID:', rayanavaService.id);
    console.log('   Slug:', rayanavaService.slug);
    console.log('   Base URL:', rayanavaService.baseUrl);

    console.log('\n📝 Generating API credentials for RAYANAVA...');

    const apiKey = generateApiKey();
    const apiSecret = generateApiSecret();
    const keyHash = hashKey(apiKey);
    const secretHash = hashKey(apiSecret);
    const keyPrefix = apiKey.substring(0, 12);

    const [createdKey] = await db.insert(externalApiKeys).values({
      name: 'RAYANAVA Gateway API Key',
      description: 'Primary API key for RAYANAVA AI Gateway ecosystem integration',
      keyHash,
      keyPrefix,
      secretHash,
      scopes: [
        'ecosystem:read',
        'ecosystem:write',
        'service:rayanava',
        'ai:chat',
        'ai:generate',
        'ai:analyze'
      ],
      rateLimit: 50000,
      rateLimitWindow: 3600,
      isActive: true,
      metadata: {
        ecosystemServiceId: rayanavaService.id,
        ecosystemSlug: 'rayanava',
        generatedFor: 'ecosystem-registry',
        autoGenerated: true,
      },
    }).returning();

    await db.update(ecosystemServices)
      .set({ apiKeyId: createdKey.id })
      .where(eq(ecosystemServices.id, rayanavaService.id));

    console.log('✅ API credentials generated');
    console.log('   Key ID:', createdKey.id);
    console.log('   Key Prefix:', keyPrefix);

    console.log('\n📝 Setting up default webhooks...');

    const defaultWebhooks = [
      {
        name: 'RAYANAVA Chat Events',
        targetUrl: `${baseUrl}/webhooks/chat`,
        events: ['chat.started', 'chat.completed', 'chat.error'],
      },
      {
        name: 'RAYANAVA Content Events',
        targetUrl: `${baseUrl}/webhooks/content`,
        events: ['content.generated', 'content.moderated', 'content.published'],
      },
      {
        name: 'RAYANAVA System Events',
        targetUrl: `${baseUrl}/webhooks/system`,
        events: ['system.health', 'system.error', 'system.metrics'],
      },
    ];

    const createdWebhooks = [];
    for (const webhook of defaultWebhooks) {
      const secret = generateWebhookSecret();
      const [created] = await db.insert(ecosystemWebhooks).values({
        serviceId: rayanavaService.id,
        name: webhook.name,
        targetUrl: webhook.targetUrl,
        events: webhook.events,
        secret,
        isActive: true,
        maxRetries: 3,
      }).returning();
      createdWebhooks.push(created);
      console.log(`   ✅ Created webhook: ${webhook.name}`);
    }

    console.log('\n📝 Creating API documentation entry...');

    const [apiDoc] = await db.insert(ecosystemApiDocs).values({
      serviceId: rayanavaService.id,
      title: 'RAYANAVA AI Gateway API',
      openApiSpec: {
        openapi: '3.0.0',
        info: {
          title: 'RAYANAVA AI Gateway API',
          description: 'API for Molochain AI Assistant - RAYANAVA',
          version: '1.0.0',
        },
        paths: {
          '/chat': {
            post: {
              summary: 'Send chat message',
              tags: ['Chat'],
              requestBody: {
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      properties: {
                        message: { type: 'string' },
                        context: { type: 'object' },
                      },
                      required: ['message'],
                    },
                  },
                },
              },
              responses: {
                '200': {
                  description: 'Chat response',
                  content: {
                    'application/json': {
                      schema: {
                        type: 'object',
                        properties: {
                          response: { type: 'string' },
                          conversationId: { type: 'string' },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
          '/generate': {
            post: {
              summary: 'Generate content',
              tags: ['Content Generation'],
              requestBody: {
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      properties: {
                        prompt: { type: 'string' },
                        type: { type: 'string', enum: ['text', 'code', 'summary'] },
                        options: { type: 'object' },
                      },
                      required: ['prompt'],
                    },
                  },
                },
              },
              responses: {
                '200': {
                  description: 'Generated content',
                },
              },
            },
          },
          '/health': {
            get: {
              summary: 'Health check',
              tags: ['System'],
              responses: {
                '200': {
                  description: 'Service is healthy',
                },
              },
            },
          },
        },
        components: {
          securitySchemes: {
            apiKey: {
              type: 'apiKey',
              name: 'X-API-Key',
              in: 'header',
            },
            apiSecret: {
              type: 'apiKey',
              name: 'X-API-Secret',
              in: 'header',
            },
          },
        },
        security: [
          { apiKey: [], apiSecret: [] },
        ],
      },
      version: '1.0.0',
      isPublished: true,
      lastSync: new Date(),
    }).returning();

    console.log('✅ API documentation created');
    console.log('   Doc ID:', apiDoc.id);

    console.log('\n' + '='.repeat(60));
    console.log('🎉 RAYANAVA Integration Seeding Complete!');
    console.log('='.repeat(60));
    console.log('\n📋 Summary:');
    console.log('   Service ID:', rayanavaService.id);
    console.log('   Service Slug:', rayanavaService.slug);
    console.log('   API Key ID:', createdKey.id);
    console.log('   Webhooks Created:', createdWebhooks.length);
    console.log('   Documentation ID:', apiDoc.id);

    console.log('\n⚠️  IMPORTANT: Save these credentials securely!');
    console.log('   API Key:', apiKey);
    console.log('   API Secret:', apiSecret);
    console.log('   Webhook Secret:', webhookSecret);
    console.log('\n   These credentials will NOT be shown again.');

    return rayanavaService;

  } catch (error) {
    console.error('❌ Error seeding RAYANAVA integration:', error);
    throw error;
  }
}

export { seedRayanavaIntegration };

const isMainModule = import.meta.url === `file://${process.argv[1]}` || 
                     process.argv[1]?.endsWith('seed-rayanava-integration.ts');

if (isMainModule) {
  seedRayanavaIntegration()
    .then(() => {
      console.log('\n✅ Seed script completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('\n❌ Seed script failed:', error);
      process.exit(1);
    });
}
