import { db } from '../core/database/db.service';
import { pageModules } from '@db/schema';

// Define initial page and module data based on existing application structure
const initialModules = [
  // Public Pages
  {
    name: 'home',
    displayName: 'Home',
    type: 'page' as const,
    category: 'public' as const,
    path: '/',
    componentPath: '@/pages/Home',
    description: 'Main landing page',
    icon: 'Home',
    parentId: null,
    order: 1,
    isActive: true,
    isVisible: true,
    requiresAuth: false,
  },
  {
    name: 'about',
    displayName: 'About',
    type: 'page' as const,
    category: 'public' as const,
    path: '/about',
    componentPath: '@/pages/About',
    description: 'About the company',
    icon: 'Info',
    parentId: null,
    order: 2,
    isActive: true,
    isVisible: true,
    requiresAuth: false,
  },
  {
    name: 'services',
    displayName: 'Services',
    type: 'page' as const,
    category: 'public' as const,
    path: '/services',
    componentPath: '@/pages/Services',
    description: 'Service offerings',
    icon: 'Briefcase',
    parentId: null,
    order: 3,
    isActive: true,
    isVisible: true,
    requiresAuth: false,
  },
  {
    name: 'contact',
    displayName: 'Contact',
    type: 'page' as const,
    category: 'public' as const,
    path: '/contact',
    componentPath: '@/pages/Contact',
    description: 'Contact information',
    icon: 'Phone',
    parentId: null,
    order: 4,
    isActive: true,
    isVisible: true,
    requiresAuth: false,
  },

  // Protected Pages
  {
    name: 'dashboard',
    displayName: 'Dashboard',
    type: 'page' as const,
    category: 'protected' as const,
    path: '/dashboard',
    componentPath: '@/pages/MainDashboard',
    description: 'User dashboard',
    icon: 'LayoutDashboard',
    parentId: null,
    order: 10,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
  },
  {
    name: 'projects',
    displayName: 'Projects',
    type: 'page' as const,
    category: 'protected' as const,
    path: '/projects',
    componentPath: '@/pages/Projects',
    description: 'Project management',
    icon: 'FolderOpen',
    parentId: null,
    order: 11,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
  },

  // Admin Pages
  {
    name: 'masterControl',
    displayName: 'Master Control Center',
    type: 'page' as const,
    category: 'admin' as const,
    path: '/admin',
    componentPath: '@/pages/admin/MasterControlCenter',
    description: 'Admin control panel',
    icon: 'Shield',
    parentId: null,
    order: 20,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
    requiredRole: 'admin',
  },
  {
    name: 'pageModuleManager',
    displayName: 'Page & Module Manager',
    type: 'page' as const,
    category: 'admin' as const,
    path: '/admin/page-modules',
    componentPath: '@/pages/admin/PageModuleManager',
    description: 'Manage pages and modules',
    icon: 'Package',
    parentId: null,
    order: 21,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
    requiredRole: 'admin',
  },
  {
    name: 'userManagement',
    displayName: 'User Management',
    type: 'page' as const,
    category: 'admin' as const,
    path: '/admin/users',
    componentPath: '@/pages/admin/UserManagement',
    description: 'Manage user accounts',
    icon: 'Users',
    parentId: null,
    order: 22,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
    requiredRole: 'admin',
  },
  {
    name: 'activityLogs',
    displayName: 'Activity Logs',
    type: 'page' as const,
    category: 'admin' as const,
    path: '/admin/activity',
    componentPath: '@/pages/admin/Activity',
    description: 'System activity logs',
    icon: 'Activity',
    parentId: null,
    order: 23,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
    requiredRole: 'admin',
  },
  {
    name: 'websocketHealth',
    displayName: 'WebSocket Health',
    type: 'page' as const,
    category: 'admin' as const,
    path: '/admin/websocket',
    componentPath: '@/pages/admin/WebSocketHealth',
    description: 'WebSocket connection monitoring',
    icon: 'Network',
    parentId: null,
    order: 24,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
    requiredRole: 'admin',
  },
  {
    name: 'securitySettings',
    displayName: 'Security Settings',
    type: 'page' as const,
    category: 'admin' as const,
    path: '/admin/security',
    componentPath: '@/pages/admin/SecuritySettings',
    description: 'Security configuration',
    icon: 'Lock',
    parentId: null,
    order: 25,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
    requiredRole: 'admin',
  },

  // Modules
  {
    name: 'transportModule',
    displayName: 'Transport Module',
    type: 'module' as const,
    category: 'protected' as const,
    path: '/transport',
    componentPath: '@/modules/transport/TransportDashboard',
    description: 'Transportation management module',
    icon: 'Truck',
    parentId: null,
    order: 30,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
  },
  {
    name: 'mololinkModule',
    displayName: 'MOLOLINK',
    type: 'module' as const,
    category: 'protected' as const,
    path: '/mololink',
    componentPath: '@/modules/mololink/MololinkWrapper',
    description: 'MOLOLINK marketplace module',
    icon: 'Store',
    parentId: null,
    order: 31,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
  },
  {
    name: 'marketplaceModule',
    displayName: 'Marketplace',
    type: 'module' as const,
    category: 'protected' as const,
    path: '/marketplace',
    componentPath: '@/modules/marketplace/MarketplaceConnections',
    description: 'Marketplace integrations',
    icon: 'ShoppingBag',
    parentId: null,
    order: 32,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
  },

  // Services
  {
    name: 'containerService',
    displayName: 'Container Service',
    type: 'service' as const,
    category: 'public' as const,
    path: '/services/container',
    componentPath: '@/pages/services/container',
    description: 'Container shipping services',
    icon: 'Package',
    parentId: null,
    order: 40,
    isActive: true,
    isVisible: true,
    requiresAuth: false,
  },
  {
    name: 'truckingService',
    displayName: 'Trucking Service',
    type: 'service' as const,
    category: 'public' as const,
    path: '/services/trucking',
    componentPath: '@/pages/services/trucking',
    description: 'Road transport services',
    icon: 'Truck',
    parentId: null,
    order: 41,
    isActive: true,
    isVisible: true,
    requiresAuth: false,
  },
  {
    name: 'airfreightService',
    displayName: 'Air Freight Service',
    type: 'service' as const,
    category: 'public' as const,
    path: '/services/airfreight',
    componentPath: '@/pages/services/airfreight',
    description: 'Air cargo services',
    icon: 'Plane',
    parentId: null,
    order: 42,
    isActive: true,
    isVisible: true,
    requiresAuth: false,
  },
  {
    name: 'warehousingService',
    displayName: 'Warehousing Service',
    type: 'service' as const,
    category: 'public' as const,
    path: '/services/warehousing',
    componentPath: '@/pages/services/warehousing',
    description: 'Storage and warehousing services',
    icon: 'Warehouse',
    parentId: null,
    order: 43,
    isActive: true,
    isVisible: true,
    requiresAuth: false,
  },

  // Departments
  {
    name: 'accountingDepartment',
    displayName: 'Accounting Department',
    type: 'department' as const,
    category: 'department' as const,
    path: '/departments/accounting',
    componentPath: '@/departments/accounting/pages/Dashboard',
    description: 'Accounting department dashboard',
    icon: 'Calculator',
    parentId: null,
    order: 50,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
  },
  {
    name: 'hrDepartment',
    displayName: 'Human Resources',
    type: 'department' as const,
    category: 'department' as const,
    path: '/departments/hr',
    componentPath: '@/departments/human-resources/pages/Dashboard',
    description: 'HR department dashboard',
    icon: 'Users',
    parentId: null,
    order: 51,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
  },
  {
    name: 'operationsDepartment',
    displayName: 'Operations Department',
    type: 'department' as const,
    category: 'department' as const,
    path: '/departments/operations',
    componentPath: '@/departments/operations/pages/Dashboard',
    description: 'Operations department dashboard',
    icon: 'Settings',
    parentId: null,
    order: 52,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
  },
  {
    name: 'supplyChainDepartment',
    displayName: 'Supply Chain',
    type: 'department' as const,
    category: 'department' as const,
    path: '/departments/supply-chain',
    componentPath: '@/departments/supply-chain/pages/Dashboard',
    description: 'Supply chain department dashboard',
    icon: 'Link',
    parentId: null,
    order: 53,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
  },
  {
    name: 'techDepartment',
    displayName: 'Technology & Engineering',
    type: 'department' as const,
    category: 'department' as const,
    path: '/departments/technology',
    componentPath: '@/departments/technology-engineering/pages/Dashboard',
    description: 'Tech department dashboard',
    icon: 'Cpu',
    parentId: null,
    order: 54,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
  },

  // Developer Pages
  {
    name: 'developerPortal',
    displayName: 'Developer Portal',
    type: 'page' as const,
    category: 'developer' as const,
    path: '/developer',
    componentPath: '@/pages/DeveloperPortal',
    description: 'Developer resources and tools',
    icon: 'Code',
    parentId: null,
    order: 60,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
  },
  {
    name: 'apiDocumentation',
    displayName: 'API Documentation',
    type: 'page' as const,
    category: 'developer' as const,
    path: '/developer/api-docs',
    componentPath: '@/pages/APIPolicies',
    description: 'API reference documentation',
    icon: 'FileCode',
    parentId: null,
    order: 61,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
  },
  {
    name: 'databaseSchema',
    displayName: 'Database Schema',
    type: 'page' as const,
    category: 'developer' as const,
    path: '/admin/schema',
    componentPath: '@/pages/DatabaseSchemaExplorer',
    description: 'Database structure explorer',
    icon: 'Database',
    parentId: null,
    order: 62,
    isActive: true,
    isVisible: true,
    requiresAuth: true,
    requiredRole: 'admin',
  },
];

async function seedPageModules() {
  try {
    console.log('Starting to seed page modules...');

    // Check if modules already exist
    const existingModules = await db.select().from(pageModules).limit(1);
    
    if (existingModules.length > 0) {
      console.log('Page modules already exist. Skipping seed.');
      return;
    }

    // Insert all modules
    for (const module of initialModules) {
      await db.insert(pageModules).values(module);
      console.log(`Created module: ${module.displayName}`);
    }

    console.log(`Successfully seeded ${initialModules.length} page modules!`);
  } catch (error) {
    console.error('Error seeding page modules:', error);
    throw error;
  }
}

// Run the seeder when this script is executed directly
seedPageModules()
  .then(() => {
    console.log('Seeding completed successfully');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Seeding failed:', error);
    process.exit(1);
  });

export { seedPageModules };